Avoid early return in structured OpenMP block
Technically, OpenMP does not allow early returns in structured
blocks (like `critical`). I found this because my compiler stopped
compiling MFEM with OpenMP with this error:
```
     318    fem/fe/fe_base.cpp: In member function 'void mfem::NodalFiniteEleme
            nt::CreateLexicographicFullMap(const mfem::IntegrationRule&) const'
            :
  >> 319    fem/fe/fe_base.cpp:672:9: error: invalid exit from OpenMP structure
            d block
     320      672 |       { return; }
     321          |         ^~~~~~
```

Luckily, there's a very simple way to rewrite the function so that this
does not happen: negating the "if" condition.